// Mocks generated by Mockito 5.3.0 from annotations
// in pavo11_flutter/test/data/data_sources/news_remote_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pavo11_flutter/data/core/i_remote_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IRemoteClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRemoteClient extends _i1.Mock implements _i2.IRemoteClient {
  MockIRemoteClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get(String? endpoint,
          {Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
          Invocation.method(
              #get, [endpoint], {#queryParameters: queryParameters}),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> post(String? endpoint,
          {Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
          Invocation.method(
              #post, [endpoint], {#queryParameters: queryParameters}),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> put(String? endpoint,
          {Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
          Invocation.method(
              #put, [endpoint], {#queryParameters: queryParameters}),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> delete(String? endpoint,
          {Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
          Invocation.method(
              #delete, [endpoint], {#queryParameters: queryParameters}),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
}
